import type { ChildLesson } from "@/types/child-class"

const BASE_LESSONS: ChildLesson[] = [
  // Day 1 - Alif (7 lessons)
  {
    id: 1,
    day: 1,
    title: "Alif - Introduction",
    level: "Beginner",
    arabic: "أ",
    translit: "Alif",
    rule: "First Letter",
    description: "The first letter of the Arabic alphabet",
  },
  {
    id: 2,
    day: 1,
    title: "Alif with Fatha",
    level: "Beginner",
    arabic: "أَ",
    translit: "A",
    rule: "Fatha",
    description: "Alif with Fatha vowel",
  },
  {
    id: 3,
    day: 1,
    title: "Alif with Kasrah",
    level: "Beginner",
    arabic: "أِ",
    translit: "I",
    rule: "Kasrah",
    description: "Alif with Kasrah vowel",
  },
  {
    id: 4,
    day: 1,
    title: "Alif with Dhamma",
    level: "Beginner",
    arabic: "أُ",
    translit: "U",
    rule: "Dhamma",
    description: "Alif with Dhamma vowel",
  },
  {
    id: 5,
    day: 1,
    title: "Alif with Sukoon",
    level: "Beginner",
    arabic: "أْ",
    translit: "A (silent)",
    rule: "Sukoon",
    description: "Alif with no vowel",
  },
  {
    id: 6,
    day: 1,
    title: "Alif Madd",
    level: "Beginner",
    arabic: "آ",
    translit: "Aa",
    rule: "Madd",
    description: "Long Alif sound",
  },
  {
    id: 7,
    day: 1,
    title: "Alif Practice Word",
    level: "Beginner",
    arabic: "أَمَّ",
    translit: "Amma",
    rule: "Practice",
    description: "Mother - practice word",
  },

  // Day 2 - Ba (7 lessons)
  {
    id: 8,
    day: 2,
    title: "Ba - Introduction",
    level: "Beginner",
    arabic: "ب",
    translit: "Ba",
    rule: "Second Letter",
    description: "The second letter of the Arabic alphabet",
  },
  {
    id: 9,
    day: 2,
    title: "Ba with Fatha",
    level: "Beginner",
    arabic: "بَ",
    translit: "Ba",
    rule: "Fatha",
    description: "Ba with Fatha vowel",
  },
  {
    id: 10,
    day: 2,
    title: "Ba with Kasrah",
    level: "Beginner",
    arabic: "بِ",
    translit: "Bi",
    rule: "Kasrah",
    description: "Ba with Kasrah vowel",
  },
  {
    id: 11,
    day: 2,
    title: "Ba with Dhamma",
    level: "Beginner",
    arabic: "بُ",
    translit: "Bu",
    rule: "Dhamma",
    description: "Ba with Dhamma vowel",
  },
  {
    id: 12,
    day: 2,
    title: "Ba with Sukoon",
    level: "Beginner",
    arabic: "بْ",
    translit: "B (silent)",
    rule: "Sukoon",
    description: "Ba with no vowel",
  },
  {
    id: 13,
    day: 2,
    title: "Ba Joining",
    level: "Beginner",
    arabic: "بَا",
    translit: "Baa",
    rule: "Joining",
    description: "Ba joined with Alif",
  },
  {
    id: 14,
    day: 2,
    title: "Ba Practice Word",
    level: "Beginner",
    arabic: "بَابْ",
    translit: "Baab",
    rule: "Practice",
    description: "Door - practice word",
  },

  // Day 3 - Ta (7 lessons)
  {
    id: 15,
    day: 3,
    title: "Ta - Introduction",
    level: "Beginner",
    arabic: "ت",
    translit: "Ta",
    rule: "Third Letter",
    description: "The third letter of the Arabic alphabet",
  },
  {
    id: 16,
    day: 3,
    title: "Ta with Fatha",
    level: "Beginner",
    arabic: "تَ",
    translit: "Ta",
    rule: "Fatha",
    description: "Ta with Fatha vowel",
  },
  {
    id: 17,
    day: 3,
    title: "Ta with Kasrah",
    level: "Beginner",
    arabic: "تِ",
    translit: "Ti",
    rule: "Kasrah",
    description: "Ta with Kasrah vowel",
  },
  {
    id: 18,
    day: 3,
    title: "Ta with Dhamma",
    level: "Beginner",
    arabic: "تُ",
    translit: "Tu",
    rule: "Dhamma",
    description: "Ta with Dhamma vowel",
  },
  {
    id: 19,
    day: 3,
    title: "Ta with Sukoon",
    level: "Beginner",
    arabic: "تْ",
    translit: "T (silent)",
    rule: "Sukoon",
    description: "Ta with no vowel",
  },
  {
    id: 20,
    day: 3,
    title: "Ta Joining",
    level: "Beginner",
    arabic: "تَا",
    translit: "Taa",
    rule: "Joining",
    description: "Ta joined with Alif",
  },
  {
    id: 21,
    day: 3,
    title: "Ta Practice Word",
    level: "Beginner",
    arabic: "تَابْ",
    translit: "Taab",
    rule: "Practice",
    description: "Repented - practice word",
  },

  // Day 4 - Tha (7 lessons)
  {
    id: 22,
    day: 4,
    title: "Tha - Introduction",
    level: "Beginner",
    arabic: "ث",
    translit: "Tha",
    rule: "Fourth Letter",
    description: "The fourth letter of the Arabic alphabet",
  },
  {
    id: 23,
    day: 4,
    title: "Tha with Fatha",
    level: "Beginner",
    arabic: "ثَ",
    translit: "Tha",
    rule: "Fatha",
    description: "Tha with Fatha vowel",
  },
  {
    id: 24,
    day: 4,
    title: "Tha with Kasrah",
    level: "Beginner",
    arabic: "ثِ",
    translit: "Thi",
    rule: "Kasrah",
    description: "Tha with Kasrah vowel",
  },
  {
    id: 25,
    day: 4,
    title: "Tha with Dhamma",
    level: "Beginner",
    arabic: "ثُ",
    translit: "Thu",
    rule: "Dhamma",
    description: "Tha with Dhamma vowel",
  },
  {
    id: 26,
    day: 4,
    title: "Tha with Sukoon",
    level: "Beginner",
    arabic: "ثْ",
    translit: "Th (silent)",
    rule: "Sukoon",
    description: "Tha with no vowel",
  },
  {
    id: 27,
    day: 4,
    title: "Tha Joining",
    level: "Beginner",
    arabic: "ثَا",
    translit: "Thaa",
    rule: "Joining",
    description: "Tha joined with Alif",
  },
  {
    id: 28,
    day: 4,
    title: "Tha Practice Word",
    level: "Beginner",
    arabic: "ثَابِتْ",
    translit: "Thabit",
    rule: "Practice",
    description: "Firm - practice word",
  },

  // Day 5 - Jim (7 lessons)
  {
    id: 29,
    day: 5,
    title: "Jim - Introduction",
    level: "Beginner",
    arabic: "ج",
    translit: "Jim",
    rule: "Fifth Letter",
    description: "The fifth letter of the Arabic alphabet",
  },
  {
    id: 30,
    day: 5,
    title: "Jim with Fatha",
    level: "Beginner",
    arabic: "جَ",
    translit: "Ja",
    rule: "Fatha",
    description: "Jim with Fatha vowel",
  },
  {
    id: 31,
    day: 5,
    title: "Jim with Kasrah",
    level: "Beginner",
    arabic: "جِ",
    translit: "Ji",
    rule: "Kasrah",
    description: "Jim with Kasrah vowel",
  },
  {
    id: 32,
    day: 5,
    title: "Jim with Dhamma",
    level: "Beginner",
    arabic: "جُ",
    translit: "Ju",
    rule: "Dhamma",
    description: "Jim with Dhamma vowel",
  },
  {
    id: 33,
    day: 5,
    title: "Jim with Sukoon",
    level: "Beginner",
    arabic: "جْ",
    translit: "J (silent)",
    rule: "Sukoon",
    description: "Jim with no vowel",
  },
  {
    id: 34,
    day: 5,
    title: "Jim Joining",
    level: "Beginner",
    arabic: "جَا",
    translit: "Jaa",
    rule: "Joining",
    description: "Jim joined with Alif",
  },
  {
    id: 35,
    day: 5,
    title: "Jim Practice Word",
    level: "Beginner",
    arabic: "جَمِيلْ",
    translit: "Jamil",
    rule: "Practice",
    description: "Beautiful - practice word",
  },

  // Day 6 - Ha (7 lessons)
  {
    id: 36,
    day: 6,
    title: "Ha - Introduction",
    level: "Beginner",
    arabic: "ح",
    translit: "Ha",
    rule: "Sixth Letter",
    description: "The sixth letter of the Arabic alphabet",
  },
  {
    id: 37,
    day: 6,
    title: "Ha with Fatha",
    level: "Beginner",
    arabic: "حَ",
    translit: "Ha",
    rule: "Fatha",
    description: "Ha with Fatha vowel",
  },
  {
    id: 38,
    day: 6,
    title: "Ha with Kasrah",
    level: "Beginner",
    arabic: "حِ",
    translit: "Hi",
    rule: "Kasrah",
    description: "Ha with Kasrah vowel",
  },
  {
    id: 39,
    day: 6,
    title: "Ha with Dhamma",
    level: "Beginner",
    arabic: "حُ",
    translit: "Hu",
    rule: "Dhamma",
    description: "Ha with Dhamma vowel",
  },
  {
    id: 40,
    day: 6,
    title: "Ha with Sukoon",
    level: "Beginner",
    arabic: "حْ",
    translit: "H (silent)",
    rule: "Sukoon",
    description: "Ha with no vowel",
  },
  {
    id: 41,
    day: 6,
    title: "Ha Joining",
    level: "Beginner",
    arabic: "حَا",
    translit: "Haa",
    rule: "Joining",
    description: "Ha joined with Alif",
  },
  {
    id: 42,
    day: 6,
    title: "Ha Practice Word",
    level: "Beginner",
    arabic: "حَكِيمْ",
    translit: "Hakeem",
    rule: "Practice",
    description: "Wise - practice word",
  },

  // Day 7 - Kha (7 lessons)
  {
    id: 43,
    day: 7,
    title: "Kha - Introduction",
    level: "Beginner",
    arabic: "خ",
    translit: "Kha",
    rule: "Seventh Letter",
    description: "The seventh letter of the Arabic alphabet",
  },
  {
    id: 44,
    day: 7,
    title: "Kha with Fatha",
    level: "Beginner",
    arabic: "خَ",
    translit: "Kha",
    rule: "Fatha",
    description: "Kha with Fatha vowel",
  },
  {
    id: 45,
    day: 7,
    title: "Kha with Kasrah",
    level: "Beginner",
    arabic: "خِ",
    translit: "Khi",
    rule: "Kasrah",
    description: "Kha with Kasrah vowel",
  },
  {
    id: 46,
    day: 7,
    title: "Kha with Dhamma",
    level: "Beginner",
    arabic: "خُ",
    translit: "Khu",
    rule: "Dhamma",
    description: "Kha with Dhamma vowel",
  },
  {
    id: 47,
    day: 7,
    title: "Kha with Sukoon",
    level: "Beginner",
    arabic: "خْ",
    translit: "Kh (silent)",
    rule: "Sukoon",
    description: "Kha with no vowel",
  },
  {
    id: 48,
    day: 7,
    title: "Kha Joining",
    level: "Beginner",
    arabic: "خَا",
    translit: "Khaa",
    rule: "Joining",
    description: "Kha joined with Alif",
  },
  {
    id: 49,
    day: 7,
    title: "Kha Practice Word",
    level: "Beginner",
    arabic: "خَيْرْ",
    translit: "Khair",
    rule: "Practice",
    description: "Good - practice word",
  },

  // Day 8 - Dal (7 lessons)
  {
    id: 50,
    day: 8,
    title: "Dal - Introduction",
    level: "Beginner",
    arabic: "د",
    translit: "Dal",
    rule: "Eighth Letter",
    description: "The eighth letter of the Arabic alphabet",
  },
  {
    id: 51,
    day: 8,
    title: "Dal with Fatha",
    level: "Beginner",
    arabic: "دَ",
    translit: "Da",
    rule: "Fatha",
    description: "Dal with Fatha vowel",
  },
  {
    id: 52,
    day: 8,
    title: "Dal with Kasrah",
    level: "Beginner",
    arabic: "دِ",
    translit: "Di",
    rule: "Kasrah",
    description: "Dal with Kasrah vowel",
  },
  {
    id: 53,
    day: 8,
    title: "Dal with Dhamma",
    level: "Beginner",
    arabic: "دُ",
    translit: "Du",
    rule: "Dhamma",
    description: "Dal with Dhamma vowel",
  },
  {
    id: 54,
    day: 8,
    title: "Dal with Sukoon",
    level: "Beginner",
    arabic: "دْ",
    translit: "D (silent)",
    rule: "Sukoon",
    description: "Dal with no vowel",
  },
  {
    id: 55,
    day: 8,
    title: "Dal Joining",
    level: "Beginner",
    arabic: "دَا",
    translit: "Daa",
    rule: "Joining",
    description: "Dal joined with Alif",
  },
  {
    id: 56,
    day: 8,
    title: "Dal Practice Word",
    level: "Beginner",
    arabic: "دِينْ",
    translit: "Deen",
    rule: "Practice",
    description: "Religion - practice word",
  },

  // Day 9 - Thal (7 lessons)
  {
    id: 57,
    day: 9,
    title: "Thal - Introduction",
    level: "Beginner",
    arabic: "ذ",
    translit: "Thal",
    rule: "Ninth Letter",
    description: "The ninth letter of the Arabic alphabet",
  },
  {
    id: 58,
    day: 9,
    title: "Thal with Fatha",
    level: "Beginner",
    arabic: "ذَ",
    translit: "Tha",
    rule: "Fatha",
    description: "Thal with Fatha vowel",
  },
  {
    id: 59,
    day: 9,
    title: "Thal with Kasrah",
    level: "Beginner",
    arabic: "ذِ",
    translit: "Thi",
    rule: "Kasrah",
    description: "Thal with Kasrah vowel",
  },
  {
    id: 60,
    day: 9,
    title: "Thal with Dhamma",
    level: "Beginner",
    arabic: "ذُ",
    translit: "Thu",
    rule: "Dhamma",
    description: "Thal with Dhamma vowel",
  },
  {
    id: 61,
    day: 9,
    title: "Thal with Sukoon",
    level: "Beginner",
    arabic: "ذْ",
    translit: "Th (silent)",
    rule: "Sukoon",
    description: "Thal with no vowel",
  },
  {
    id: 62,
    day: 9,
    title: "Thal Joining",
    level: "Beginner",
    arabic: "ذَا",
    translit: "Thaa",
    rule: "Joining",
    description: "Thal joined with Alif",
  },
  {
    id: 63,
    day: 9,
    title: "Thal Practice Word",
    level: "Beginner",
    arabic: "ذَاكِرْ",
    translit: "Thakir",
    rule: "Practice",
    description: "Remembering - practice word",
  },

  // Day 10 - Ra (7 lessons)
  {
    id: 64,
    day: 10,
    title: "Ra - Introduction",
    level: "Beginner",
    arabic: "ر",
    translit: "Ra",
    rule: "Tenth Letter",
    description: "The tenth letter of the Arabic alphabet",
  },
  {
    id: 65,
    day: 10,
    title: "Ra with Fatha",
    level: "Beginner",
    arabic: "رَ",
    translit: "Ra",
    rule: "Fatha",
    description: "Ra with Fatha vowel",
  },
  {
    id: 66,
    day: 10,
    title: "Ra with Kasrah",
    level: "Beginner",
    arabic: "رِ",
    translit: "Ri",
    rule: "Kasrah",
    description: "Ra with Kasrah vowel",
  },
  {
    id: 67,
    day: 10,
    title: "Ra with Dhamma",
    level: "Beginner",
    arabic: "رُ",
    translit: "Ru",
    rule: "Dhamma",
    description: "Ra with Dhamma vowel",
  },
  {
    id: 68,
    day: 10,
    title: "Ra with Sukoon",
    level: "Beginner",
    arabic: "رْ",
    translit: "R (silent)",
    rule: "Sukoon",
    description: "Ra with no vowel",
  },
  {
    id: 69,
    day: 10,
    title: "Ra Joining",
    level: "Beginner",
    arabic: "رَا",
    translit: "Raa",
    rule: "Joining",
    description: "Ra joined with Alif",
  },
  {
    id: 70,
    day: 10,
    title: "Ra Practice Word",
    level: "Beginner",
    arabic: "رَبْ",
    translit: "Rabb",
    rule: "Practice",
    description: "Lord - practice word",
  },

  // Base lessons beyond day 10 would continue following the same pattern with additional letters.
]

const createPracticeLessons = (lessons: ChildLesson[]): ChildLesson[] => {
  if (lessons.length === 0) {
    return []
  }

  const groupedByDay = new Map<number, ChildLesson[]>()
  let maxId = lessons.reduce((acc, lesson) => Math.max(acc, lesson.id), 0)
  const expandedLessons: ChildLesson[] = []

  for (const lesson of lessons) {
    const dayLessons = groupedByDay.get(lesson.day)
    if (dayLessons) {
      dayLessons.push(lesson)
    } else {
      groupedByDay.set(lesson.day, [lesson])
    }
  }

  for (const day of Array.from(groupedByDay.keys()).sort((a, b) => a - b)) {
    const dayLessons = groupedByDay.get(day)
    if (!dayLessons || dayLessons.length === 0) {
      continue
    }

    const sortedBaseLessons = [...dayLessons].sort((a, b) => a.id - b.id)
    expandedLessons.push(...sortedBaseLessons)

    const additionalLessonsNeeded = Math.max(0, 20 - sortedBaseLessons.length)

    for (let i = 0; i < additionalLessonsNeeded; i++) {
      const templateLesson = sortedBaseLessons[i % sortedBaseLessons.length]
      maxId += 1

      expandedLessons.push({
        ...templateLesson,
        id: maxId,
        title: `${templateLesson.title} Practice`,
        description: `Additional practice for ${templateLesson.title}`,
        rule: templateLesson.rule.includes("Practice")
          ? templateLesson.rule
          : `${templateLesson.rule} Practice`,
      })
    }
  }

  return expandedLessons
}

export const LESSONS: ChildLesson[] = createPracticeLessons(BASE_LESSONS)

// Helper function to get lessons by day
export const getLessonsByDay = (day: number): ChildLesson[] => {
  return LESSONS.filter((lesson) => lesson.day === day)
}

// Helper function to get total days
export const getTotalDays = (): number => {
  return Math.max(...LESSONS.map((l) => l.day))
}
